### ISSUE TITLE
ImportError: cannot import name search

### ISSUE THREAD

**Issue by Nomed1478963** [toxic-ig/Trity#1]
when i try to run trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 29, in <module>
    from search import *
  File "/opt/trity/search.py", line 1, in <module>
    from google import search
ImportError: cannot import name search

i install all google searsh module 
pip install google 
pip install google-searsh-api

and nothing change

**Comment by toxic-ig** [comment]
apt-get update
pip uninstall google
pip install google

**Comment by Zawadidone** [comment]
I am having the same problem

**Comment by toxic-ig** [comment]
Fixed.
