### ISSUE TITLE
need old version trity 

### ISSUE THREAD

**Issue by takhar1995** [toxic-ig/Trity#10]
I need old version trity please give me old version trity on vikramtakhar6@gmail.com

**Comment by frontass** [comment]
me too

**Comment by mariondudu** [comment]
I need old version trity please give me old version trity on mariondupret76@gmail.com

**Comment by mariondudu** [comment]
rebonjour vous m'avez envoyé un message mais je n'ai pas reçu trity3.2 :( , svp j'attend avec impatiente merci de votre comprehention
