### ISSUE TITLE
r = requests.get('http://pastebin.com/raw/vYcBSV4w') 

### ISSUE THREAD

**Issue by fantasy1608** [toxic-ig/Trity#10]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 149, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 70, in get
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 56, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pastebin.com', port=80): Max retries exceeded with url: /raw/vYcBSV4w (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4abb67be90>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by Senpai-Github** [comment]
@fantasy1608 
# Please explain to me the issue that you are having and what you were trying to do when you got that error
## Contact me at:
### And please have a Subject, and a description of your issue and I will get back to you in 1-2 business days
- senpai.github@outlook.com

**Comment by fantasy1608** [comment]
I can't use Trity, it show 
  ,------,------------------------------,------.
  |      |             Trity            |      |
  |      |                              |      |
  |      |------------------------------|      |
  |      ||............................||      |
  |      ||     Hack Facebook? (y/n)   ||      |
  |      ||___                      ___||      |
  |      ||---`--------------------'---||      |
  `------'|____________________________|`------'               


|----- Made by _t0x1c aka toxic -----|
|-----      Version: 3.2        -----|
|-----   1 tool - 35 choices    -----|
|-----    toxic-ig.github.io    -----|

|----- A Warm Welcome to Trity! -----|
|----- Awesome Pentesting tool! -----|
|----- Have Fun and Stay Legal! -----|
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 149, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 70, in get
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 56, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pastebin.com', port=80): Max retries exceeded with url: /raw/vYcBSV4w (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f178c7a7c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Can you help me?? thanks!

**Comment by Senpai-Github** [comment]
@fantasy1608 
First, `git clone`.

     git clone https://github.com/toxic-ig/Trity.git

Change directory, and then run the installer script (Must be root or have superuser permissions):

    cd path/Trity
    sudo python install.py

The `install.py` script will install of the necessary dependencies for you.
Once you are finished ther, the execute it with the command:

    trity




### However if you already did all of this, please uninstall the program and try again. If that doesn't work please let me know and also tell me what you did during the installation

please contact me at:

senpai@trityapp.net

**Comment by fantasy1608** [comment]
I try to reinstall and it show 
`Failed building wheel for readline
  Running setup.py clean for readline
Failed to build readline
Installing collected packages: readline
  Running setup.py install for readline ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3DANVa/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e1PUZG-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'readline' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/Modules
    creating build/temp.linux-x86_64-2.7/Modules/2.x
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-x86_64-2.7/Modules/2.x/readline.o -Wno-strict-prototypes
    creating build/lib.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/readline.so
    /usr/bin/ld: cannot find -lncurses
    collect2: error: ld returned 1 exit status
    **error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**
    
    ----------------------------------------
**Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3DANVa/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e1PUZG-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3DANVa/readline/**
[!] Finished Installing! Run 'trity' to run program [!]
`
Can you help me??? Thanks

**Comment by fantasy1608** [comment]
I try `sudo apt-get install lib32ncurses5-dev` and install without error but when i type `tryti` it show 
`Traceback (most recent call last):
  File "/opt/trity/trity.py", line 149, in <module>
    r = requests.get('http://pastebin.com/raw/vYcBSV4w') 
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 70, in get
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 56, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pastebin.com', port=80): Max retries exceeded with url: /raw/vYcBSV4w (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb0ea950450>: Failed to establish a new connection: [Errno -2] Name or service not known',))
`
Screenshot
[https://goo.gl/photos/R2aDEoy5n4Yi7EK48](url)

**Comment by fantasy1608** [comment]
Just change DNS and it work well
