### ISSUE TITLE
Could not find a version that satisfies the requirement PIL

### ISSUE THREAD

**Issue by gearcapitan** [toxic-ig/Trity#13]
Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
![kali linux-2017-04-26-09-29-10](https://cloud.githubusercontent.com/assets/13740942/25439838/34b31398-2a63-11e7-8107-65717acc03cc.png)
![kali linux-2017-04-26-09-30-50](https://cloud.githubusercontent.com/assets/13740942/25439846/39c2ace0-2a63-11e7-9382-ea7f369f0cdc.png)

**Comment by ph3n0m79** [comment]
I am having the same issue on Kali 2017.1

I was able to pip install mechanize, but after re-running the install script, I still get the below error:

Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
[!] Finished Installing! Run 'trity' to run program [!]

When I attempt to run Trity I get a bunch of downloads again, then it brings me back to the root prompt.

**Comment by toxic-ig** [comment]
Fixed.
