### ISSUE TITLE
Import Error. Kindly telll how to resolve this issue

### ISSUE THREAD

**Issue by skdawar** [toxic-ig/Trity#15]
Operating Systems Available: 

--------------------------
(1) Kali Linux / Ubuntu 
--------------------------

[>] Select Operating System: 1
[*] Loading...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "install.py", line 30, in <module>
    import pip
ImportError: No module named pip

**Comment by toxic-ig** [comment]
Fixed
