### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skdawar** [toxic-ig/Trity#16]
python-easygui python-levenshtein python-metaconfig
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2004 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncurses5 is already the newest version (6.0+20161126-1).
The following packages were automatically installed and are no longer required:
  gnome-mime-data java-wrappers libadns1 libbonobo2-0 libbonobo2-common
  libgif4 libgnome-2-0 libgnome2-common libgnomevfs2-0 libgnomevfs2-common
  libgnomevfs2-extra liborbit-2-0 maltegoce python-adns python-distlib
  python-easygui python-levenshtein python-metaconfig
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2004 not upgraded.
Traceback (most recent call last):
  File "install.py", line 44, in <module>
    pip.main(["install", "netifaces", "PIL", "scapy", "SpoofMAC", "pythonwhois", "readline", "BeautifulSoup", "requests", "mechanize", "google", "qrcode"])
NameError: name 'pip' is not defined

**Comment by toxic-ig** [comment]
Fixed
