### ISSUE TITLE
issue with File "/opt/trity/trity.py", FIX FIX FIX

### ISSUE THREAD

**Issue by mrrobot85** [toxic-ig/Trity#18]
guys.. a lot of people has been having issues with trying to open trity after installing it.. here is the fix..

there is a folder inside the trity folder called "trity"... copy/cut all the files inside that folder and paste into the main trity folder were the install file etc is.. it's that simple.. then delete the empty trity folder..

you're welcome.. now simply either type trity or python trity.py from the trity directory and boom... there you go..

**Comment by yhk6** [comment]
i did that but it doesn't seem to work. removed and reinstalled still nothing nothing. 
i get an error on install : 

Command "/usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-build-LDcx64/readline/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-Vv0BIY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-LDcx64/readline/

**Comment by toxic-ig** [comment]
Fixed. Try to run it again. Reinstall it and install Trity again.
