### ISSUE TITLE
Trity Spoof Email ISP

### ISSUE THREAD

**Issue by Eno123456** [toxic-ig/Trity#2]
When I try to run the spoof email, it asked for what I want to pose as - expected, my real email - expected, and my ISP - Unexpected. My ISP is Verizon but it still doesn't work when under isp I type Verizon. Why is the ISP needed and how do I get It to work?

**Comment by toxic-ig** [comment]
You need to put your ISP address in.

**Comment by yashaizen** [comment]
What do you mean by ISP address? I have an IP address and the name of my ISP ..How to find ISP address?

**Comment by Vancer** [comment]
@toxic-ig  I wish you would have explained to @yashaizen  more. 
@yashaizen  Here is what you need to do, navigate to the website of your ISP. Then once you get the url for example: https://www.myisp.net/ then you navigate to:
 [https://itsecuritysector.com/Exterma-Server-Scanner/]
Then put your ISP's website there as: myisp.net.lb (Note: make sure you strip the lashes out with the https:// ) 
Then hit Scan. then once the scan is over, check the mail servers. One of them should be inserted in the ISP field in trity.

**Comment by yashaizen** [comment]
Hello @Vancer .  Thanks for explaining. I have done as you mentioned and got few mail servers. 
The problem i am facing now is it shows 1 of the 3 errors :
 1. Timeout   
 2. MTA not trusted
 3. Connection Refused. 
Please help me through this.
