### ISSUE TITLE
trity start issue

### ISSUE THREAD

**Issue by MeanMachine123** [toxic-ig/Trity#20]
~/Trity# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 27, in <module>
    from searchs import *
  File "/opt/trity/searchs.py", line 1, in <module>
    from google import search
ImportError: cannot import name search

**Comment by MeanMachine123** [comment]
Only trity had a issue in my system except other 50 tools

**Comment by matteso** [comment]
did you find a fix? i'm experiencing the same problem :/

**Comment by MeanMachine123** [comment]
Trity is the only tool where should I got a PROBLEM in 100's :(

________________________________

**Comment by toxic-ig** [comment]
Fixed. Re-install Trity from Github.

**Comment by MeanMachine123** [comment]
Issue has been resolved.Thanks All Dude. Trity is working fine now 😊
________________________________
