### ISSUE TITLE
Trity error

### ISSUE THREAD

**Issue by Mustafa1986** [toxic-ig/Trity#21]
When I run trity, I faced with  following  error.  What am I doing wrong? Please help!!!
# Traceback (most recent call last):
  File "/opt/trity/trity.py", line 27, in <module>
    from searchs import *
  File "/opt/trity/searchs.py", line 1, in <module>
    from google import search
ImportError: No module named google

**Comment by akagrey** [comment]
same problem :(

**Comment by Mustafa1986** [comment]
Why the author does not answer fir this problem ? :-1:

**Comment by eudomoniacc** [comment]
cd /opt/trity
leafpad searchs.py
change "from google import search" to "from googlesearch import search"

Done

**Comment by Mustafa1986** [comment]
thanks bro , everything works. @eudomoniacc

**Comment by eudomoniacc** [comment]
Rica ederim ;) @Mustafa1986

**Comment by toxic-ig** [comment]
Fixed. Re-install Trity from Github.
