### ISSUE TITLE
ImportError: cannot import name search

### ISSUE THREAD

**Issue by matteso** [toxic-ig/Trity#22]
Whenever I try to run the program I get this error. 

root@kali:~/Desktop/Trity# trity
Traceback (most recent call last)
        File "opt/trity/trity.py" , line 27 in <module>
            from searchs import *
        File "opt/trity/searchs.py" , line 1 in <module>
            from google import search
ImportError: cannot import name search

before this it was giving me an error saying that there was no google module so i did sudo pip install google.py and it seemed to work, but now I get this error. Any ideas as to wha's happening?

**Comment by eudomoniacc** [comment]
cd /opt/trity
leafpad searchs.py
change "from google import search" to "from googlesearch import search"

Done

**Comment by toxic-ig** [comment]
Fixed. Re-install Trity from Github.

**Comment by damienrobins** [comment]
Thanks. Juat checked the mail.
