### ISSUE TITLE
cannot import name search error in kali linux

### ISSUE THREAD

**Issue by RackoS** [toxic-ig/Trity#23]
I downloaded Trity and ı ınstalled it but it is not working. I tried a few program and ı try kali linux in virtualbox but it is not working
only working on parrot os

the first time error is "no module named google"
I fix that but this time there is this error

PLS Help Me

https://user-images.githubusercontent.com/35405544/34909068-7b228bd8-f8a3-11e7-83a3-a1cbff4f1838.png

sorry for my english
Kali Linux 2017.3

**Comment by eudomoniacc** [comment]
cd /opt/trity
leafpad searchs.py
change "from google import search" to "from googlesearch import search"

Done

**Comment by RackoS** [comment]
thanks so much:))

**Comment by toxic-ig** [comment]
Fixed. Re-install Trity from Github.
