### ISSUE TITLE
ImportError: No module named google

### ISSUE THREAD

**Issue by huntsman1** [toxic-ig/Trity#24]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 27, in <module>
    from searchs import *
  File "/opt/trity/searchs.py", line 1, in <module>
    from google import search
ImportError: No module named google

**Comment by eudomoniacc** [comment]
cd /opt/trity
leafpad searchs.py
change "from google import search" to "from googlesearch import search"

Done

**Comment by DPTFox** [comment]
After changing the "searchs.py" header to the recommended line above. Now receiving:
##
You don't have some modules installed! 
Please run install.py to install this tool fully! 
Error: No module named google
Execute: pip install (module name)
##

Google module is satisfied according to system
##
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from google)
##

**Comment by eudomoniacc** [comment]
pip install google==2.0.1

**Comment by DPTFox** [comment]
Requirement already satisfied: google==2.0.1 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from google==2.0.1)

**Comment by eudomoniacc** [comment]
Then you can use google-search module but you have to modify both searchs.py and trity.py.

**Comment by DPTFox** [comment]
/opt/trity/searchs.py
"from google import search"
to
"from googlesearch import search"

/opt/trity/trity.py
"import google"
to
"import googlesearch"

Success. Thank you.

**Comment by toxic-ig** [comment]
Fixed.
