### ISSUE TITLE
Error after install !! 

### ISSUE THREAD

**Issue by yhk6** [toxic-ig/Trity#24]
I GET THIS ERROR AFTER INSTALL.. I DONT UNDERSTAND WHAT I MEANS . PLZ HELP 
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-LDcx64/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Vv0BIY-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-LDcx64/readline/ 

When i try to start i get : 
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 88, in <module>
    if 'no' in open('trity/agree.txt').read():# take out the trity/
IOError: [Errno 2] No such file or directory: 'trity/agree.txt'

**Comment by d0geda** [comment]
Make agree.txt file with "yes" in it and move it to trity folder

**Comment by d0geda** [comment]
``cd /opt/trity
``gedit trity.py
and remove trity/ on line 88 in path and also on line 101 in path

**Comment by d0geda** [comment]
And if you don't want to see the Update warning just do....
```
cd /opt/trity
gedit trity.py
```
and comment line 149
and change line  151 to `if False:`

**Comment by toxic-ig** [comment]
Fixed. Try to run it again. Reinstall it and install Trity again.

**Comment by yhk6** [comment]
@d0geda SOLVED !! thank you !!
