### ISSUE TITLE
ImportError: No module named googlesearch

### ISSUE THREAD

**Issue by trollmad3** [toxic-ig/Trity#27]
I am currently getting an error that says this:

```
Traceback (most recent call last):
 File "/opt/trity/trity.py", line 27, in <module>
from searches import *
File "/opt/trity/searches", line 1 in <module>
from googlesearch import search
ImportError: No module named googlesearch
```

I tried two different ways thinking that it will fix it such as

1. Uninstalling and reinstalling
2. Going to /opt/trity/searches and seeing the problem

**Comment by apu745** [comment]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 13, in <module>
    from info import *
>>>>>>>>>>>>not slove after re install ,plz help

**Comment by trollmad3** [comment]
@apu745 The creator said that this program will be removed due to him makeing a newer better one.

**Comment by toxic-ig** [comment]
Fixed. Reinstall trity

**Comment by trollmad3** [comment]
@toxic-ig What is the command to uninstall trity? is it `rm -rf`?
