### ISSUE TITLE
problem install [Kali Linux 2017.1]

### ISSUE THREAD

**Issue by gaiththewolf** [toxic-ig/Trity#30]
when i try to install : process stop with problem in => ImportError: No module named pip
--Some Help-- My Trace --
root@kali:~/Desktop/Ext_App# chmod -R 777 Trity/
root@kali:~/Desktop/Ext_App/Trity# ls -lA /usr/local/bin | grep pip
-rwxr-xr-x 1 root staff     361 juin  21 06:37 pip
-rwxr-xr-x 1 root staff     363 juin  21 06:37 pip2
-rwxr-xr-x 1 root staff     367 juin  21 06:37 pip2.7
root@kali:~/Desktop/Ext_App/Trity# python install.py 

  ------------------
< Trity Installer!! >
  ------------------
         \   ^__^
          \  (oo)\_______
             (__)\       )\/
                 ||-----||
                 ||     ||

Operating Systems Available: 

--------------------------
(1) Kali Linux / Ubuntu / Raspbian
--------------------------

[>] Select Operating System: 1
[*] Loading...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
Traceback (most recent call last):
  File "install.py", line 31, in <module>
    import pip
ImportError: No module named pip
root@kali:~/Desktop/Ext_App/Trity# 

-- End --
Thanks

**Comment by gaiththewolf** [comment]
i resove it by this : 
--|
root@kali:~/Desktop/Ext_App/Trity#  /usr/bin/python -V
Python 2.7.13
root@kali:~/Desktop/Ext_App/Trity# /usr/local/bin/python -V
Python 2.6.6
--|End
and i add to install.py : #!/usr/bin/python

**Comment by toxic-ig** [comment]
Fixed
