### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by adeelahmad3163** [toxic-ig/Trity#4]
![screenshot from 2017-08-03 15 46 13](https://user-images.githubusercontent.com/30681422/28945245-9ad6ff6c-789d-11e7-9657-0a253fd4ed08.png)

**Comment by toxic-ig** [comment]
Are you using the newest version of Kali?

**Comment by adeelahmad3163** [comment]
No its a previous version

**Comment by toxic-ig** [comment]
Well try updating your kali, like hop onto a newer version @adeelahmad3163

**Comment by adeelahmad3163** [comment]
Thankuu
