### ISSUE TITLE
Unable to locate package lib32ncurses5-dev

### ISSUE THREAD

**Issue by allandoug** [toxic-ig/Trity#4]
When you install Trity, the following error message appears:

root@allan:/home/allan/Área de Trabalho/Trity# trity
  File "/opt/trity/trity.py", line 49
    elif (e) == "Unable to locate package lib32ncurses5-dev"
                                                           ^
SyntaxError: invalid syntax

**Comment by zolarious** [comment]
Hello, this is just a typo error in the code
you shall go to the file trity.py located in /opt/trity , open it with any text editor, go to line 49 where this elif statement
elif (e) == "Unable to locate package lib32ncurses5-dev"

just add " : " to the end of the line - without the semi-column to correct the syntax error, it should be like that
elif (e) == "Unable to locate package lib32ncurses5-dev":

save and run
