### ISSUE TITLE
unable to locate package: lib32ncurses5

### ISSUE THREAD

**Issue by mickhacks** [toxic-ig/Trity#5]
root@kali2016:/home/allan/Área de Trabalho/Trity# trity
File "/opt/trity/trity.py", line 49
elif (e) == "Unable to locate package lib32ncurses5-dev"
^
SyntaxError: invalid syntax

**Comment by zolarious** [comment]
Hello, this is just a typo error in the code
you shall go to the file trity.py located in /opt/trity and go to line 49 

just add " : " to the end of the line - without the semi-column to correct the syntax error 

save and run
