### ISSUE TITLE
Trity username and password to install it on Desktop

### ISSUE THREAD

**Issue by ahmedgc01** [toxic-ig/Trity#6]
please guide us which username and password are used to clone it on kali machine . I even created account on git hub for safe side to do this smoothly but I'm vain .

**Comment by Subham7373** [comment]
Same problem

**Comment by sajol4e** [comment]
Me to

**Comment by sajol4e** [comment]
Please fix that problem ....or remove the password....

**Comment by Senpai-Github** [comment]
# **_Username & Password should be unnecessary_**
## If you are trying to git clone it to your computer do as follows:
### git clone https://github.com/toxic-ig/Trity.git ~/wherever/you/want/the/program

@ahmedgc01 @Subham7373 @sajol4e @toxic-ig 
If you are not doing that step, please comment below mine so I know where you are and I may be of assistance if that doesn't help

**Comment by toxic-ig** [comment]
Fixed. Question not relevant and clear.
