### ISSUE TITLE
Running on this command : Python truth.py

### ISSUE THREAD

**Issue by prabhu16ece** [toxic-ig/Trity#8]

**Comment by prabhu16ece** [comment]
![1491028654623372024704](https://cloud.githubusercontent.com/assets/26739658/24576137/d9946efa-16d3-11e7-974b-2f0957ab3c93.jpg)
Pls help me creator I want to know ho q to use trity

**Comment by sreecodeslayer** [comment]
Please read the instructions, it clearly says to install Trity using the instructions in the README file.

```bash
sudo python install.py
```
This, as mentioned in the README will install all the required modules. After than you can use the framework.

**Comment by toxic-ig** [comment]
sudo python install.py and then follow the instructions on screen @prabhu16ece
